
.PHONY: all
all: 
	$(MAKE) all -C rnn-learn
	$(MAKE) all -C rnn-generate
	$(MAKE) all -C python
	$(MAKE) all -C unit-test

.PHONY: clean
clean:
	$(MAKE) clean -C rnn-learn
	$(MAKE) clean -C rnn-generate
	$(MAKE) clean -C python
	$(MAKE) clean -C unit-test

